### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by droter** [Welltory/Zoom2Youtube#1]
Hi,

Thanks for putting together this script.

When I run $make build I get the following error:

Err:6 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists...
E: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu bionic Release' does not have a Release file.
ERROR: Service 'app' failed to build: The command '/bin/sh -c add-apt-repository ppa:jonathonf/python-3.6' returned a non-zero code: 100
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 1

Is there an updated link?

Thanks,

Matt

**Comment by radist101** [comment]
Hi, we fixed container build
